### ISSUE TITLE
各種センサーデバイスに対応し照度計にも対応、ライブラリーとしてpython-switchbotを使用、機微情報のイメージへの埋め込みを廃止

### ISSUE THREAD

**Issue by hkato** [tanny-pm/switchbot-dashboard#1]
Zennでコメントした者です。こちらをベースに次の変更を行ったのですが、プルリクエストを投げてよろしいでしょうか？動作確認はHub 2でしか行えていません。
    
- 温湿度計(Meter)、防水温湿度計(WoIOSensor)、加湿器(Humidifier)、ハブ2(Hub 2)にも対応
- 照度(lightLevel)に対応(現在の対応デバイスはHub 2のみ)
- 機微情報(.envのトークンやデバイスIDの含まれたJSONファイル)をイメージに埋め込むのを廃止(dotenvを削除)
- PyPIで公開されているpython-switchbotライブラリーを使用する方法に変更(switchbot.pyは削除)
- typing-extensions関連がpython-switchbotとinflux-clientで互換性がないので他のライブラリーも含めてアップデート
- フルパッケージは不要なのでコンテナイメージを小さくするためにslimイメージを利用

[python-switchbot](https://github.com/jonghwanhyeon/python-switchbot)は[こちら](https://pypi.org/project/python-switchbot/)です。他のライブラリーも見てみましたが、こちらが一通りの機能が揃ってそうなので…

python-switchbotを使ったりDocker周りをいじっていたりと設計方針と異なる様でしたらスミマセン。

**Comment by hkato** [comment]
フォーク先の変更はこちらです。

https://github.com/tanny-pm/switchbot-dashboard/compare/main...hkato:switchbot-influxdb:main

**Comment by hkato** [comment]
スミマセン取り下げます。別途自分の方は更新していきます。

**Comment by tanny-pm** [comment]
GitHubを見ておらず、すぐに返信ができませんでした。失礼いたしました🙏

**Comment by hkato** [comment]
承知しました。かなり改変して別物になってしまったので自分の方は自分でやっていきます。

// ちなみに、初代Meterを入手予定なのでそちらもあわせてテストしてみます。
